Use ES6 Syntax.
digitalbazaar/bedrock-angular-session pull request #5
Opened 2017-05-22 22:00 UTC by mattcollier

2017-05-22 22:58 UTC, dlongley requested changes

2017-05-22 22:58 UTC, dlongley commented on bedrock/components/login/login.js
> +import loginController from './login-controller';
Typo? `loginController` => `LoginController`

2017-05-22 22:58 UTC, dlongley commented on bedrock/components/main.js
> +import LoginLogin from './login/login';
This is a little weird... something misnamed?

2017-05-23 01:13 UTC, mattcollier commented
@dlongley ready for another pass.

2017-05-23 13:43 UTC, dlongley approved these changes

2017-05-23 21:42 UTC, davidlehn approved these changes

2017-05-26 23:22 UTC, merged